// flow-typed signature: 735ac87e8f85b08e4f29479b86fb7015
// flow-typed version: <<STUB>>/bootstrap_v4.0.0-alpha.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/npm' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/button' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/umd/util' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/bs-commonjs-generator' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/change-version' {
  declare module.exports: any;
}

declare module 'bootstrap/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap'>;
}
declare module 'bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.min'>;
}
declare module 'bootstrap/dist/js/npm.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/npm'>;
}
declare module 'bootstrap/dist/js/umd/alert.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/alert'>;
}
declare module 'bootstrap/dist/js/umd/button.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/button'>;
}
declare module 'bootstrap/dist/js/umd/carousel.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/carousel'>;
}
declare module 'bootstrap/dist/js/umd/collapse.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/collapse'>;
}
declare module 'bootstrap/dist/js/umd/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/dropdown'>;
}
declare module 'bootstrap/dist/js/umd/modal.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/modal'>;
}
declare module 'bootstrap/dist/js/umd/popover.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/popover'>;
}
declare module 'bootstrap/dist/js/umd/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/scrollspy'>;
}
declare module 'bootstrap/dist/js/umd/tab.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/tab'>;
}
declare module 'bootstrap/dist/js/umd/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/tooltip'>;
}
declare module 'bootstrap/dist/js/umd/util.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/umd/util'>;
}
declare module 'bootstrap/grunt/bs-commonjs-generator.js' {
  declare module.exports: $Exports<'bootstrap/grunt/bs-commonjs-generator'>;
}
declare module 'bootstrap/grunt/change-version.js' {
  declare module.exports: $Exports<'bootstrap/grunt/change-version'>;
}
declare module 'bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap/Gruntfile'>;
}
