// flow-typed signature: ad5a80c4241eb25d579a4e442c7a0a92
// flow-typed version: <<STUB>>/mozilla-neo_v2.7.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mozilla-neo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mozilla-neo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mozilla-neo/commands/build/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/generator/initializing' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/generator/install' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/generator/prompting' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/generator/writing' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/about/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/app' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/home/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/layout/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/nav/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/src/routes' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/tests/about_test' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/tests/home_test' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/tests/layout_test' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/init/templates/tests/nav_test' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/start/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/test/index' {
  declare module.exports: any;
}

declare module 'mozilla-neo/commands/test/karma.conf' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/babel' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/eslint.core' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/eslint.dev' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/karma' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/webpack.core' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/webpack.dev' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/webpack.prod' {
  declare module.exports: any;
}

declare module 'mozilla-neo/config/webpack.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mozilla-neo/commands/build/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/build/index'>;
}
declare module 'mozilla-neo/commands/init/generator/initializing.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/generator/initializing'>;
}
declare module 'mozilla-neo/commands/init/generator/install.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/generator/install'>;
}
declare module 'mozilla-neo/commands/init/generator/prompting.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/generator/prompting'>;
}
declare module 'mozilla-neo/commands/init/generator/writing.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/generator/writing'>;
}
declare module 'mozilla-neo/commands/init/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/about/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/about/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/app.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/app'>;
}
declare module 'mozilla-neo/commands/init/templates/src/home/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/home/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/layout/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/layout/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/nav/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/nav/index'>;
}
declare module 'mozilla-neo/commands/init/templates/src/routes.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/src/routes'>;
}
declare module 'mozilla-neo/commands/init/templates/tests/about_test.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/tests/about_test'>;
}
declare module 'mozilla-neo/commands/init/templates/tests/home_test.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/tests/home_test'>;
}
declare module 'mozilla-neo/commands/init/templates/tests/layout_test.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/tests/layout_test'>;
}
declare module 'mozilla-neo/commands/init/templates/tests/nav_test.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/init/templates/tests/nav_test'>;
}
declare module 'mozilla-neo/commands/start/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/start/index'>;
}
declare module 'mozilla-neo/commands/test/index.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/test/index'>;
}
declare module 'mozilla-neo/commands/test/karma.conf.js' {
  declare module.exports: $Exports<'mozilla-neo/commands/test/karma.conf'>;
}
declare module 'mozilla-neo/config/babel.js' {
  declare module.exports: $Exports<'mozilla-neo/config/babel'>;
}
declare module 'mozilla-neo/config/eslint.core.js' {
  declare module.exports: $Exports<'mozilla-neo/config/eslint.core'>;
}
declare module 'mozilla-neo/config/eslint.dev.js' {
  declare module.exports: $Exports<'mozilla-neo/config/eslint.dev'>;
}
declare module 'mozilla-neo/config/karma.js' {
  declare module.exports: $Exports<'mozilla-neo/config/karma'>;
}
declare module 'mozilla-neo/config/webpack.core.js' {
  declare module.exports: $Exports<'mozilla-neo/config/webpack.core'>;
}
declare module 'mozilla-neo/config/webpack.dev.js' {
  declare module.exports: $Exports<'mozilla-neo/config/webpack.dev'>;
}
declare module 'mozilla-neo/config/webpack.prod.js' {
  declare module.exports: $Exports<'mozilla-neo/config/webpack.prod'>;
}
declare module 'mozilla-neo/config/webpack.test.js' {
  declare module.exports: $Exports<'mozilla-neo/config/webpack.test'>;
}
