// flow-typed signature: 2ae07abc91df6aa41175f053d0860fab
// flow-typed version: <<STUB>>/redux-devtools-chart-monitor_v1.4.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-chart-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-chart-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-chart-monitor/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-devtools-chart-monitor/lib/Chart' {
  declare module.exports: any;
}

declare module 'redux-devtools-chart-monitor/lib/ChartMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-chart-monitor/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-chart-monitor/lib/reducers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-chart-monitor/lib/actions.js' {
  declare module.exports: $Exports<'redux-devtools-chart-monitor/lib/actions'>;
}
declare module 'redux-devtools-chart-monitor/lib/Chart.js' {
  declare module.exports: $Exports<'redux-devtools-chart-monitor/lib/Chart'>;
}
declare module 'redux-devtools-chart-monitor/lib/ChartMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-chart-monitor/lib/ChartMonitor'>;
}
declare module 'redux-devtools-chart-monitor/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-chart-monitor/lib/index'>;
}
declare module 'redux-devtools-chart-monitor/lib/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-chart-monitor/lib/reducers'>;
}
