// flow-typed signature: 3927923c651f8963337a8d6afa6cec03
// flow-typed version: <<STUB>>/spy_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spy/lib/call' {
  declare module.exports: any;
}

declare module 'spy/lib/equal' {
  declare module.exports: any;
}

declare module 'spy/lib/proto' {
  declare module.exports: any;
}

declare module 'spy/lib/spy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spy/index' {
  declare module.exports: $Exports<'spy'>;
}
declare module 'spy/index.js' {
  declare module.exports: $Exports<'spy'>;
}
declare module 'spy/lib/call.js' {
  declare module.exports: $Exports<'spy/lib/call'>;
}
declare module 'spy/lib/equal.js' {
  declare module.exports: $Exports<'spy/lib/equal'>;
}
declare module 'spy/lib/proto.js' {
  declare module.exports: $Exports<'spy/lib/proto'>;
}
declare module 'spy/lib/spy.js' {
  declare module.exports: $Exports<'spy/lib/spy'>;
}
